### ISSUE TITLE
techpack/audio/kconfig something in config is wrong

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#2274] opened 2020-05-31 02:38 UTC
techpack/Kconfig:1: can't open file "techpack/audio/Kconfig"
make[1]: * [scripts/kconfig/Makefile:113: aosp_tone_dora_defconfig] Error 1
make: * [Makefile:534: aosp_tone_dora_defconfig] Error 2

**Comment by ghost** [comment] 2020-05-31 02:39
Please fix for Sony X and XZ

**Comment by kholk** [comment] 2020-05-31 07:58
You have to clone the techpacks gits to the proper folders. This is not a bug.

Besides that, please use the bug tracker next time.

**Comment by ghost** [comment] 2020-05-31 17:57
I have to clone which one?

**Comment by MartinX3** [comment] 2020-05-31 18:19
I assume you search this
https://www.github.com/sonyxperiadev/local_manifests

**Comment by ix5** [comment] 2020-05-31 19:25
Follow [the Kernel compilation guide](https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices) to the letter and you will not have the issues you describe.

For your benefit, the issue lies in the fact that you are trying to compile a 4.14 kernel, which relies on git submodules.
The submodules and their location can be found in the [local_manifests xml file for the 4.14 kernel](https://github.com/sonyxperiadev/local_manifests/blob/2061f1b0129d2550e8318c05337e3dd730a5a958/LA.UM.7.1.r1.xml#L6-L12).

But your devices are not supported on 4.14 yet: Both Xperia X ("suzu") on the loire platform as well as Xperia XZ ("kagura") on the tone platform are only supported on 4.9.

Please close this issue.

**Comment by ix5** [comment] 2020-05-31 19:26
@jerpelea you might want to turn off the "Issues" functionality for this repo altogether, and redirect people to the common bug tracker.

**Closed as completed** 2020-06-01 04:42 UTC
